# Generated by Django 4.2.5 on 2023-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('COMETA', 'Cometa'), ('ESTRELA', 'Estrela'), ('GALAXIA', 'Galáxia'), ('NEBULOSA', 'Nebulosa'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
